require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/companions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Companion. As you add validations to Companion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Companion.create! valid_attributes
      get companions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      companion = Companion.create! valid_attributes
      get companion_url(companion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_companion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      companion = Companion.create! valid_attributes
      get edit_companion_url(companion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Companion" do
        expect {
          post companions_url, params: { companion: valid_attributes }
        }.to change(Companion, :count).by(1)
      end

      it "redirects to the created companion" do
        post companions_url, params: { companion: valid_attributes }
        expect(response).to redirect_to(companion_url(Companion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Companion" do
        expect {
          post companions_url, params: { companion: invalid_attributes }
        }.to change(Companion, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post companions_url, params: { companion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested companion" do
        companion = Companion.create! valid_attributes
        patch companion_url(companion), params: { companion: new_attributes }
        companion.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the companion" do
        companion = Companion.create! valid_attributes
        patch companion_url(companion), params: { companion: new_attributes }
        companion.reload
        expect(response).to redirect_to(companion_url(companion))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        companion = Companion.create! valid_attributes
        patch companion_url(companion), params: { companion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested companion" do
      companion = Companion.create! valid_attributes
      expect {
        delete companion_url(companion)
      }.to change(Companion, :count).by(-1)
    end

    it "redirects to the companions list" do
      companion = Companion.create! valid_attributes
      delete companion_url(companion)
      expect(response).to redirect_to(companions_url)
    end
  end
end
